spring:
  application:
    name: api-zuul

  http:
    encoding:
      force: true
      force-request: true
      force-response: true
    converters:
      preferred-json-mapper: jackson
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql#root
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/apps/

debug: true

