spring:
  application:
    name: api-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql#root
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF8&serverTimezone=GMT&useUnicode=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

server:
  port: 8762
  http2:
    enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/apps/

debug: true
